--- a/.github/workflows/integration_test.yml
+++ b/.github/workflows/integration_test.yml
@@ -39,4 +39,4 @@
 
       - name: Run integration test
         run: |
-          bash test/integration_test/run.sh
+          bash test/integration_test/run.sh